Make it a real object
PrimarySite/django-recaptcha2 pull request #2
Opened 2017-06-05 09:35 UTC by roebuk

2017-06-05 10:38 UTC, Briggy2501 approved these changes
Recreated this change locally to test recaptcha, worked fine for me. LGTM

2017-06-05 11:19 UTC, SammyM requested changes

2017-06-05 11:19 UTC, SammyM commented on snowpenguin/django/recaptcha2/templates/snowpenguin/recaptcha/recaptcha_init.html
> -    window.addEventListener('load', function() {
Put this indentation back please.

2017-06-05 11:19 UTC, SammyM commented on snowpenguin/django/recaptcha2/templates/snowpenguin/recaptcha/recaptcha_init.html
>  <script>
Indent this within the Django `if` please.

2017-06-05 11:19 UTC, SammyM commented on snowpenguin/django/recaptcha2/templates/snowpenguin/recaptcha/recaptcha_init.html
> +    var id = grecaptcha.render(el.id, Object.assign({}, el.dataset));
`Id` isn't a very descriptive variable name.

2017-06-05 11:19 UTC, SammyM commented on snowpenguin/django/recaptcha2/templates/snowpenguin/recaptcha/recaptcha_init.html
> +    el.setAttribute('data-captchaId', id);
I'm pretty sure this can just be `el.dataset.captchaId  = id;`

2017-06-05 11:41 UTC, SammyM commented on snowpenguin/django/recaptcha2/templates/snowpenguin/recaptcha/recaptcha_init.html
> +    var id = grecaptcha.render(el.id, Object.assign({}, el.dataset));
`Object.assign` is not supported in IE11.

2017-06-06 10:38 UTC, SammyM approved these changes

2017-06-07 10:05 UTC, merged